services:
  flask:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads/resumes:/app/uploads/resumes
      - flask_data:/app/instance

  vue:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

volumes:
  flask_data:
