services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"


  flask:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
      - flask_data:/app/instance

    depends_on:
      - redis


  celery_worker:
    build: ./backend
    command: celery -A app.jobs.celery_app.celery worker --loglevel=info
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - ./backend/uploads:/app/uploads
      - flask_data:/app/instance

    depends_on:
      - redis

    restart: unless-stopped


  celery_beat:
    build: ./backend
    command: celery -A app.jobs.celery_app.celery beat --loglevel=info --schedule=/app/celerybeat/celerybeat-schedule
    env_file:
      - .env
    volumes:
      - ./backend/app:/app/app
      - flask_data:/app/instance
      - celerybeat_data:/app/celerybeat
    depends_on:
      - redis

    restart: unless-stopped

  vue:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true


volumes:
  flask_data:
  celerybeat_data:
